export var allowPages = [
  'error',
  'listener',
  'codeshare',
  'giveback',
  'feedetail',
  'followreward',
  'shareshop',
  'familyDetail',
  'familyMember',
  'handlesuperflow',
  'checkin',
  'promisefee',
  'instockfees',
  'redirect',
  'emp(/)?.*',
  'tvaddfee',
  'consobusiness'
].join('|');
