// BASE_BANNERS_INFO
export const BASE_BANNERS_ACTION = 'BASE_BANNERS_ACTION';
export const BASE_BANNERS_CLEAN = 'BASE_BANNERS_CLEAN';
export const BASE_BANNERS_REQUEST = 'BASE_BANNERS_REQUEST';
export const BASE_BANNERS_SUCCESS = 'BASE_BANNERS_SUCCESS';
export const BASE_BANNERS_FAILURE = 'BASE_BANNERS_FAILURE';

// BASE_MODULES_INFO
export const BASE_DZGMODULES_ACTION = 'BASE_DZGMODULES_ACTION';
export const BASE_DZGMODULES_CLEAN = 'BASE_DZGMODULES_CLEAN';
export const BASE_DZGMODULES_REQUEST = 'BASE_DZGMODULES_REQUEST';
export const BASE_DZGMODULES_SUCCESS = 'BASE_DZGMODULES_SUCCESS';
export const BASE_DZGMODULES_FAILURE = 'BASE_DZGMODULES_FAILURE';
